# The action creates structure from terraform file and deploys the pecipes application.
name: deploy_app
# action trigger
on: 
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  # jobs name
  build_infrastructure:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Check programs
        run: aws --version
             terrform --version
             
        # Git action script what clones the repository on runer.
      - name: Clone repo
        run: aws --actions/checkout@v1    

      - name: List folder and move to terraform folder
        run: ls -la
             cd ./terraform
             ls -la
            

    
    
