# The action creates structure from terraform file and deploys the pecipes application.
name: deploy_app
# action trigger
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  # jobs name
  build_infrastructure:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Check programm version
        run: |
          aws --version
          terraform --version
             
      # Git action script what clones the repository on runer.
      - name: Clone repo
        uses: actions/checkout@v3    

      - name: List folder and move to terraform folder
        run: 
          ls -la
          cd ./terraform
          ls -la
            

    
    
