name: start_app

env:
  S3_BUCKET_NAME: test-bucket-gj-190
  
on:
  workflow_dispatch:

jobs:
  start_recipes_application:
    runs-on: ubuntu-latest
    
    steps:
 
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1
             
      - name: Clone repo into runner
        uses: actions/checkout@v3  

      - name: Check does exist S3 Bucket with the name
        run: |
          if aws s3api list-buckets --query "Buckets[].Name" | grep -w "${{ env.S3_BUCKET_NAME }}"; then
            echo "S3 bucket '$bucket_name' exists."
            exit 0
          else
            echo "S3 bucket '$bucket_name' does not exist."
            exit 1
