name: test

on:
  workflow_dispatch:

jobs:
  create_app_ifrastructure:
    runs-on: ubuntu-latest
    
    steps:
 
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1
          
      - name: Get public IP and deassotiate it from MySQL instance
        run: |
          pubid=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=RecipesMySQL" Name=instance-state-name,Values=running --query "Reservations[*].Instances[*].InstanceId" --output text)
          echo "$pubid"
          allid=$(aws ec2 associate-address --instance-id $pubid --allocation-id eipalloc-0f4f5a55bf15bdff1)
          echo "$allid"
          aws ec2 disassociate-address --association-id $allid

            
